### PR TITLE
ConditionalBuilder now implements DependencyDeclarer

### PR DESCRIPTION
**Pull request by TWestling**
SingleConditionalBuilder already implements the correct
DependencyDeclarer. This change makes it so that
ConditionalBuilder does the same.

This is needed to get downstream functionality of e.g. the Junit plugin aggregation and downstream- buildview to work.

### CODE REVIEW

**Comment by TWestling** [comment]
@imod Could you take a look at this? It is basically the same as https://github.com/jenkinsci/conditional-buildstep-plugin/pull/10 but for the multi step instead of single step.

**Comment by imod** [comment]
@TWestling looks good to me - I'll merge is in the next couple of days

**Comment by TWestling** [comment]
@imod I noticed that this doesn't work as is for e.g. the parameterized trigger, nor does it work for pull #10  Since we add every builder to the dependencygraph, even if the condition returns false, the graph will make sure that it runs anyway. This is solved in the flexible-publish plugin so the simplest solution is to add a dependency to flexible-publish. I'll add that change to this pull request, please have a look.

**Comment by imod** [comment]
@TWestling sorry, I don't like the dependency to the flexible-publish - can't we just do it the same way as it is done there?

**Comment by TWestling** [comment]
@imod I was thinking you would say that :) 
It looks like the support is mostly done by 2 classes so sure, I can copy those over here. I will update this PR with the changes, probably next week.

**Comment by imod** [comment]
@TWestling any plans to finish this?

**Comment by TWestling** [comment]
@imod Yes, this slipped my mind as we started using my version of the plugin and then I forgot about it. I'll reopen it now.

**Comment by TWestling** [comment]
@ikedam I've copied two of your classes from the flexible-publish-plugin in order to get the dependency graph to work as it should. I copied them in as they were and just added a note regarding where they came from, I hope this is ok.

**Comment by ikedam** [comment]
@TWestling Looks good to me.

**Comment by TWestling** [comment]
@imod I removed the dependency to the flexible-publisher plugin, could you have a look?

**Comment by imod** [comment]
👍

**Pull request merged**
