### PR TITLE
[JENKINS-35561] Migrate conditional-build-step-plugin to 2.x parent pom

### PR DESCRIPTION
**Pull request by fbelzunc**
https://issues.jenkins-ci.org/browse/JENKINS-35561

@reviewbybees @andresrc @armfergom

### CODE REVIEW

**Comment by fbelzunc** [comment]
@armfergom do you know where the NPE comes from?

**Comment by oleg-nenashev** [comment]
@fbelzunc Do you mean your last commit or the test failure?

**Comment by oleg-nenashev** [comment]
Seems Jenkins Test Harness version should be adjusted as well. There are library version conflicts

**Comment by fbelzunc** [comment]
@oleg-nenashev I was talking about the test failure

> Seems Jenkins Test Harness version should be adjusted as well. There are library version conflicts

Would you  mind to explain this a bit more elaborate, please?

**Comment by andresrc** [comment]
The build errors seem related to the typical `HttpComponents` conflict.

Please run `mvn dependency:tree` to see which version is using and the dependency trail.

**Comment by andresrc** [comment]
@fbelzunc @oleg-nenashev these conflicts are quite common with new versions of the JTH. I'm proposing an "approach" to simplify handling it in https://github.com/andresrc/jenkins-test-harness-htmlunit/pull/1

**Comment by fbelzunc** [comment]
@andresrc 

```
Felixs-MBP:conditional-buildstep-plugin fbelzunc$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Conditional BuildStep 1.3.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ conditional-buildstep ---
[INFO] org.jenkins-ci.plugins:conditional-buildstep:hpi:1.3.4-SNAPSHOT
[INFO] +- org.jenkins-ci.plugins:token-macro:jar:1.5.1:compile
[INFO] +- org.jenkins-ci.plugins:run-condition:jar:1.0:compile
[INFO] +- org.jenkins-ci.main:maven-plugin:jar:2.8:compile
[INFO] |  +- org.jenkins-ci.plugins:javadoc:jar:1.0:compile
[INFO] |  +- org.jenkins-ci.plugins:mailer:jar:1.7:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven-agent:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven-interceptor:jar:1.6:compile
[INFO] |  +- org.jvnet.hudson:maven2.1-interceptor:jar:1.2:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven3-agent:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven31-agent:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven32-agent:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven3-interceptor:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven31-interceptor:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven32-interceptor:jar:1.6:compile
[INFO] |  +- org.jenkins-ci.main.maven:maven3-interceptor-commons:jar:1.6:compile
[INFO] |  +- org.apache.maven:maven-core:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-repository-metadata:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-plugin-api:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-model-builder:jar:3.1.0:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.16:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-utils:jar:3.0.10:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO] |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |  +- org.apache.maven:maven-compat:jar:3.1.0:compile
[INFO] |  +- org.apache.maven:maven-aether-provider:jar:3.1.0:compile
[INFO] |  +- org.apache.maven:maven-embedder:jar:3.1.0:compile
[INFO] |  |  +- org.sonatype.plexus:plexus-cipher:jar:1.7:compile
[INFO] |  |  \- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  +- org.eclipse.aether:aether-api:jar:0.9.0.M3:compile
[INFO] |  +- org.eclipse.aether:aether-impl:jar:0.9.0.M3:compile
[INFO] |  +- org.eclipse.aether:aether-spi:jar:0.9.0.M3:compile
[INFO] |  +- org.eclipse.aether:aether-util:jar:0.9.0.M3:compile
[INFO] |  +- org.eclipse.aether:aether-transport-wagon:jar:0.9.0.M3:compile
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5:compile
[INFO] |  |  +- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |  |  \- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M5:compile
[INFO] |  +- com.google.inject:guice:jar:no_aop:4.0-beta:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.apache.maven.wagon:wagon-http:jar:2.4:compile
[INFO] |  |  \- org.apache.maven.wagon:wagon-http-shared4:jar:2.4:compile
[INFO] |  |     \- org.jsoup:jsoup:jar:1.7.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.2.5:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.2.4:compile
[INFO] |  +- org.apache.maven.wagon:wagon-file:jar:2.4:compile
[INFO] |  +- org.apache.maven.wagon:wagon-ftp:jar:2.4:compile
[INFO] |  |  \- commons-net:commons-net:jar:3.1:compile
[INFO] |  +- org.apache.maven.wagon:wagon-ssh:jar:2.4:compile
[INFO] |  |  +- com.jcraft:jsch:jar:0.1.44-1:compile
[INFO] |  |  \- org.apache.maven.wagon:wagon-ssh-common:jar:2.4:compile
[INFO] |  |     \- org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-6:compile
[INFO] |  +- org.apache.maven.wagon:wagon-ssh-external:jar:2.4:compile
[INFO] |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.4:compile
[INFO] |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
[INFO] |  |  \- org.apache.maven.doxia:doxia-sink-api:jar:1.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.1:compile
[INFO] |  +- org.jenkins-ci.lib:lib-jenkins-maven-artifact-manager:jar:1.2:compile
[INFO] |  +- org.jenkins-ci.lib:lib-jenkins-maven-embedder:jar:3.11:compile
[INFO] |  |  \- org.eclipse.aether:aether-connector-wagon:jar:0.9.0.M2:compile
[INFO] |  +- org.apache.maven.wagon:wagon-webdav-jackrabbit:jar:2.4:compile
[INFO] |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:2.4:compile
[INFO] |  |  \- org.apache.jackrabbit:jackrabbit-webdav:jar:2.5.2:compile
[INFO] |  \- org.jenkins-ci:SECURITY-144-compat:jar:1.0:compile
[INFO] +- org.jenkins-ci.plugins:matrix-project:jar:1.0-beta-1:compile
[INFO] +- com.google.code.findbugs:annotations:jar:3.0.0:provided
[INFO] +- net.jcip:jcip-annotations:jar:1.0:provided
[INFO] +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:provided
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:test
[INFO] +- javax.servlet:servlet-api:jar:2.4:provided
[INFO] +- org.jenkins-ci.main:jenkins-core:jar:1.580.1:provided
[INFO] |  +- org.jenkins-ci.plugins.icon-shim:icon-set:jar:1.0.3:provided
[INFO] |  +- org.jenkins-ci.main:remoting:jar:2.47:provided
[INFO] |  |  \- org.jenkins-ci:constant-pool-scanner:jar:1.2:provided
[INFO] |  +- org.jenkins-ci.main:cli:jar:1.580.1:provided
[INFO] |  +- org.jenkins-ci:version-number:jar:1.1:provided
[INFO] |  +- org.jenkins-ci:crypto-util:jar:1.1:provided
[INFO] |  +- org.jvnet.hudson:jtidy:jar:4aug2000r7-dev-hudson-1:provided
[INFO] |  +- org.jruby.ext.posix:jna-posix:jar:1.0.3:provided
[INFO] |  +- com.github.jnr:jnr-posix:jar:3.0.1:provided
[INFO] |  |  +- com.github.jnr:jnr-ffi:jar:1.0.7:provided
[INFO] |  |  |  +- com.github.jnr:jffi:jar:1.2.7:provided
[INFO] |  |  |  +- com.github.jnr:jffi:jar:native:1.2.7:provided
[INFO] |  |  |  +- org.ow2.asm:asm:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-analysis:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-tree:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-util:jar:4.0:provided
[INFO] |  |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:provided
[INFO] |  |  \- com.github.jnr:jnr-constants:jar:0.8.5:provided
[INFO] |  +- org.kohsuke:trilead-putty-extension:jar:1.2:provided
[INFO] |  +- org.jenkins-ci:trilead-ssh2:jar:build217-jenkins-5:provided
[INFO] |  +- org.kohsuke.stapler:stapler-groovy:jar:1.231:provided
[INFO] |  |  \- org.kohsuke.stapler:stapler-jelly:jar:1.231:provided
[INFO] |  |     +- org.jenkins-ci:commons-jelly:jar:1.1-jenkins-20120928:provided
[INFO] |  |     \- org.jenkins-ci.dom4j:dom4j:jar:1.6.1-jenkins-4:provided
[INFO] |  +- org.kohsuke.stapler:stapler-jrebel:jar:1.231:provided
[INFO] |  |  \- org.kohsuke.stapler:stapler:jar:1.231:provided
[INFO] |  |     +- javax.annotation:javax.annotation-api:jar:1.2:provided
[INFO] |  |     +- commons-discovery:commons-discovery:jar:0.4:provided
[INFO] |  |     \- org.jvnet:tiger-types:jar:1.3:provided
[INFO] |  +- org.kohsuke:windows-package-checker:jar:1.0:provided
[INFO] |  +- org.kohsuke.stapler:stapler-adjunct-zeroclipboard:jar:1.3.5-1:provided
[INFO] |  +- org.kohsuke.stapler:stapler-adjunct-timeline:jar:1.4:provided
[INFO] |  +- org.kohsuke.stapler:stapler-adjunct-codemirror:jar:1.3:provided
[INFO] |  +- com.infradna.tool:bridge-method-annotation:jar:1.13:provided
[INFO] |  +- org.kohsuke.stapler:json-lib:jar:2.4-jenkins-2:provided
[INFO] |  |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:provided
[INFO] |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  +- args4j:args4j:jar:2.0.23:provided
[INFO] |  +- org.jenkins-ci:annotation-indexer:jar:1.7:provided
[INFO] |  +- org.jenkins-ci:bytecode-compatibility-transformer:jar:1.5:provided
[INFO] |  |  \- org.kohsuke:asm5:jar:5.0.1:provided
[INFO] |  +- org.jenkins-ci:task-reactor:jar:1.4:provided
[INFO] |  +- org.jvnet.localizer:localizer:jar:1.10:provided
[INFO] |  +- antlr:antlr:jar:2.7.6:provided
[INFO] |  +- org.jvnet.hudson:xstream:jar:1.4.7-jenkins-1:provided
[INFO] |  +- jfree:jfreechart:jar:1.0.9:provided
[INFO] |  |  \- jfree:jcommon:jar:1.0.12:provided
[INFO] |  +- org.apache.ant:ant:jar:1.8.3:compile
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.8.3:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- commons-digester:commons-digester:jar:2.1:provided
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.8.3:provided
[INFO] |  +- javax.mail:mail:jar:1.4.4:provided
[INFO] |  +- org.jvnet.hudson:activation:jar:1.1.1-hudson-1:provided
[INFO] |  +- jaxen:jaxen:jar:1.1-beta-11:provided
[INFO] |  +- commons-jelly:commons-jelly-tags-fmt:jar:1.0:provided
[INFO] |  +- commons-jelly:commons-jelly-tags-xml:jar:1.1:provided
[INFO] |  +- org.jvnet.hudson:commons-jelly-tags-define:jar:1.0.1-hudson-20071021:provided
[INFO] |  +- org.jenkins-ci:commons-jexl:jar:1.1-jenkins-20111212:provided
[INFO] |  +- org.acegisecurity:acegi-security:jar:1.0.7:provided
[INFO] |  |  +- org.springframework:spring-jdbc:jar:1.2.9:provided
[INFO] |  |  |  \- org.springframework:spring-dao:jar:1.2.9:provided
[INFO] |  |  +- oro:oro:jar:2.0.8:provided
[INFO] |  |  \- log4j:log4j:jar:1.2.17:provided
[INFO] |  +- org.codehaus.groovy:groovy-all:jar:1.8.9:provided
[INFO] |  +- jline:jline:jar:0.9.94:provided
[INFO] |  +- org.fusesource.jansi:jansi:jar:1.9:provided
[INFO] |  +- org.springframework:spring-webmvc:jar:2.5.6.SEC03:provided
[INFO] |  |  +- org.springframework:spring-beans:jar:2.5.6.SEC03:provided
[INFO] |  |  +- org.springframework:spring-context:jar:2.5.6.SEC03:provided
[INFO] |  |  +- org.springframework:spring-context-support:jar:2.5.6.SEC03:provided
[INFO] |  |  \- org.springframework:spring-web:jar:2.5.6.SEC03:provided
[INFO] |  +- org.springframework:spring-core:jar:2.5.6.SEC03:provided
[INFO] |  +- org.springframework:spring-aop:jar:2.5.6.SEC03:provided
[INFO] |  +- xpp3:xpp3:jar:1.1.4c:provided
[INFO] |  +- javax.servlet:jstl:jar:1.1.0:provided
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:provided
[INFO] |  +- com.sun.xml.txw2:txw2:jar:20110809:provided
[INFO] |  |  +- javax.xml.stream:stax-api:jar:1.0-2:provided
[INFO] |  |  \- relaxngDatatype:relaxngDatatype:jar:20020414:provided
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:provided
[INFO] |  +- org.jvnet.winp:winp:jar:1.22:provided
[INFO] |  +- org.jenkins-ci:memory-monitor:jar:1.8:provided
[INFO] |  +- org.codehaus.woodstox:wstx-asl:jar:3.2.9:provided
[INFO] |  |  \- stax:stax-api:jar:1.0.1:provided
[INFO] |  +- org.jenkins-ci:jmdns:jar:3.4.0-jenkins-3:provided
[INFO] |  +- net.java.dev.jna:jna:jar:3.3.0-jenkins-3:provided
[INFO] |  +- org.kohsuke:akuma:jar:1.9:provided
[INFO] |  +- org.kohsuke:libpam4j:jar:1.6:provided
[INFO] |  +- org.jvnet.libzfs:libzfs:jar:0.5:provided
[INFO] |  +- com.sun.solaris:embedded_su4j:jar:1.1:provided
[INFO] |  +- net.java.sezpoz:sezpoz:jar:1.9:provided
[INFO] |  +- org.kohsuke.jinterop:j-interop:jar:2.0.6-kohsuke-1:provided
[INFO] |  |  \- org.kohsuke.jinterop:j-interopdeps:jar:2.0.6-kohsuke-1:provided
[INFO] |  |     \- org.samba.jcifs:jcifs:jar:1.2.19:provided
[INFO] |  +- org.jvnet.robust-http-client:robust-http-client:jar:1.2:provided
[INFO] |  +- commons-codec:commons-codec:jar:1.8:compile
[INFO] |  +- org.kohsuke:access-modifier-annotation:jar:1.4:provided
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.3.1-jenkins-1:provided
[INFO] |  +- org.mindrot:jbcrypt:jar:0.3m:provided
[INFO] |  +- com.google.guava:guava:jar:11.0.1:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  \- com.jcraft:jzlib:jar:1.1.3-kohsuke-1:provided
[INFO] +- org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.580.1:test
[INFO] |  +- org.jenkins-ci.modules:instance-identity:jar:1.4:test
[INFO] |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.47:test
[INFO] |  |     \- org.bouncycastle:bcprov-jdk15on:jar:1.47:test
[INFO] |  +- org.jenkins-ci.modules:ssh-cli-auth:jar:1.2:test
[INFO] |  +- org.jenkins-ci.modules:slave-installer:jar:1.3:test
[INFO] |  +- org.jenkins-ci.modules:windows-slave-installer:jar:1.4:test
[INFO] |  +- org.jenkins-ci.modules:launchd-slave-installer:jar:1.2:test
[INFO] |  +- org.jenkins-ci.modules:upstart-slave-installer:jar:1.1:test
[INFO] |  +- org.jenkins-ci.modules:systemd-slave-installer:jar:1.1:test
[INFO] |  \- org.jenkins-ci.modules:sshd:jar:1.6:test
[INFO] |     \- org.apache.sshd:sshd-core:jar:0.8.0:test
[INFO] |        \- org.apache.mina:mina-core:jar:2.0.5:test
[INFO] +- org.jenkins-ci.main:jenkins-war:war:1.580.1:test
[INFO] +- org.jenkins-ci.main:jenkins-test-harness:jar:2.6:test
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.2.15.v20160210:test
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.2.15.v20160210:test
[INFO] |  |  |  \- org.eclipse.jetty:jetty-util:jar:9.2.15.v20160210:test
[INFO] |  |  \- org.eclipse.jetty:jetty-servlet:jar:9.2.15.v20160210:test
[INFO] |  +- org.eclipse.jetty:jetty-security:jar:9.2.15.v20160210:test
[INFO] |  |  \- org.eclipse.jetty:jetty-server:jar:9.2.15.v20160210:test
[INFO] |  |     +- org.eclipse.jetty:jetty-http:jar:9.2.15.v20160210:test
[INFO] |  |     \- org.eclipse.jetty:jetty-io:jar:9.2.15.v20160210:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- net.sourceforge.htmlunit:htmlunit:jar:2.18:test
[INFO] |  |  +- xalan:xalan:jar:2.7.2:test
[INFO] |  |  |  \- xalan:serializer:jar:2.7.2:test
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.4:test
[INFO] |  |  +- org.apache.httpcomponents:httpmime:jar:4.5:test
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.17:test
[INFO] |  |  +- xerces:xercesImpl:jar:2.11.0:test
[INFO] |  |  |  \- xml-apis:xml-apis:jar:1.4.01:test
[INFO] |  |  +- net.sourceforge.nekohtml:nekohtml:jar:1.9.22:test
[INFO] |  |  +- net.sourceforge.cssparser:cssparser:jar:0.9.16:test
[INFO] |  |  |  \- org.w3c.css:sac:jar:1.3:test
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.2.12.v20150709:test
[INFO] |  |     \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.12.v20150709:test
[INFO] |  |        \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.12.v20150709:test
[INFO] |  +- org.jvnet.hudson:embedded-rhino-debugger:jar:1.2:test
[INFO] |  +- org.netbeans.modules:org-netbeans-insane:jar:RELEASE72:test
[INFO] |  \- com.github.stephenc.findbugs:findbugs-annotations:jar:1.3.9-1:test
[INFO] +- org.jenkins-ci:test-annotations:jar:1.2:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] +- org.slf4j:log4j-over-slf4j:jar:1.7.7:test
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.7:test
[INFO] \- org.slf4j:slf4j-jdk14:jar:1.7.7:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.567 s
[INFO] Finished at: 2016-06-13T09:17:53+02:00
[INFO] Final Memory: 31M/448M
[INFO] ------------------------------------------------------------------------
```

**Comment by andresrc** [comment]
@fbelzunc please try with parent pom 2.11

**Comment by stephenc** [comment]
@fbelzunc ping

**Comment by imod** [comment]
@fbelzunc will you work on this again?

**Comment by imod** [comment]
replaced by #14

**Pull request closed without merging**
