### PR TITLE
Update matrix-project version 

### PR DESCRIPTION
**Pull request by pc-mreeves**
- Update to current version because beta version no longer seems to be available from http://updates.jenkins-ci.org/download/plugins/matrix-project/

### CODE REVIEW

**Comment by pc-mreeves** [comment]
I am not sure if I need to do anything else than this. I come more from a devops perspective and discovered when I try to install the conditional-buildstep-plugin in a chef cookbook it appears to try to download a matrix-project version that does not exist (it tries http://updates.jenkins-ci.org/download/plugins/matrix-project/1.0.pre.beta.pre.1/matrix-project.hpi). I chose 1.7.1 which appears to work for me but an alternative would be to use version 1.0.

**Comment by pc-mreeves** [comment]
@imod - Anything else I need to do here?

**Comment by imod** [comment]
no, I just did not see that you have opened this PR - maybe next time just open a JIRA issue and assign it to me.

I try to take care of it in the next couple of days...

**Comment by imod** [comment]
@pc-mreeves I shortly checked this - the problem is, that matrix 1.7.1 depends on core 1.609, but this plugin only on core 1.580.1. So to merge this, we also need to lift conditional-buildstep to 1.609.

will take a look?

**Comment by jacobfike** [comment]
👍 I am in the same boat, installing this plugin through chef is failing because of the matrix-project plugin.  At the very least can you release a version that doesn't need the beta version of matrix-project?

**Comment by pc-mreeves** [comment]
@jacobfike I came up with a workaround.

I install the matrix-project plugin and other deps first and restart jenkins and when I install this plugin I tell it not to install deps.

In attributes/default.json I have:
```
'matrix-project' => { notifies: [ :restart, 'service[jenkins]', :immediately ] }, # dep of conditional-buildstep
'maven-plugin' => { notifies: [ :restart, 'service[jenkins]', :immediately ] }, # dep of conditional-buildstep
'run-condition' => { notifies: [ :restart, 'service[jenkins]', :immediately ] }, # dep of conditional-buildstep
'conditional-buildstep' => { install_deps: false }, # prevent install of broken matrix-project version
```
and then I have a plugins.rb recipe that utilizes the [jenkins cookbook in supermarket](https://supermarket.chef.io/cookbooks/jenkins):
```
node[:jenkins][:master][:plugins].each do |plugin, params|
  # log "installing jenkins plugin: #{plugin}, params: #{params.to_s}" # debugging

  jenkins_plugin plugin do
    retries 5
    retry_delay 5
    version params[:version].to_s if params.key?(:version)
    install_deps params[:install_deps] if params.key?(:install_deps)
    notifies *params[:notifies] if params.key?(:notifies) # note splat operator
    options params[:options] if params.key?(:options)
  end
```

**Comment by pc-mreeves** [comment]
@imod - Sorry, I lost the thread on this but will look into it. I am actually running this on jenkins 2.37 and it appears to run fine. 1.580 is from 2014/09/21 and 1.609 is from 2015/04/12 per https://jenkins.io/changelog/ . Are there some tests we could run or something?

**Comment by imod** [comment]
@pc-mreeves there are some tests in the project already, sure there could be more, but it gives a first impression. You could also run some of your builds with a SNAPSHOT version of this plugin and I will then do some more tests my self as well.

**Pull request closed without merging**
